version: '3.0'
services:
  mongodb:
    image: mongo:6.0
    restart: on-failure
    ports:
      - '27017:27017'
    networks:
      - application_network

  nestapi:
    build: .
    volumes:
      - ./usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - mongodb
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/car-rent
    networks:
      - application_network

networks:
  application_network: